SELECT ROUND(AVG(TB.LAT_N), 4)
FROM (SELECT LAT_N, ROW_NUMBER() OVER(ORDER BY LAT_N) AS R, COUNT(LAT_N) OVER() AS TOTAL
FROM STATION) AS TB
WHERE (TB.TOTAL%2 = 0 AND TB.R IN (TB.TOTAL/2, TB.TOTAL/2+1)) OR (TB.TOTAL%2 = 1 AND TB.R = (TB.TOTAL+1)/2);
